### ISSUE TITLE
in minimal example only off seems to work

### ISSUE THREAD

**Issue by fkgruber** [toddmedema/echo#1]
Hi
I tried the minimal example and only the OFF command works. I think another commenter on instructable found the same issue. Is this an easy fix?

thanks
F

**Comment by toddmedema** [comment]
Hey F,

Sorry, just saw this... notification email must've went to spam. Were you able to get it to work?

Thank you,

Todd

**Comment by ebartz** [comment]
@fkgruber I can not reproduce this. For me this works well

On the minimal example you will have to do something like this:

``` python

if state:
      # do something to turn it on
    else:
      # do something else to turn it off
```

**Comment by fkgruber** [comment]
Not sure what was the issue but it is working quite well now thanks

**Comment by bjoern494** [comment]
Hello,
I just had the same issue. Here, only "on" was working but. The  "off" did not even reach the RaspPi.

THE PROBLEM WAS:
I called the group "test", I nice name i thought. But unfortunally, "Alexa, turn test off" was not processed as wemo command. Renaming the group to something else than "test" resolved the issue .

**Comment by toddmedema** [comment]
Nice teamwork! Sounds like this is closed, then?
